project: 
  type: website

website:
  title: "Josh Schaefer Data Science Portfolio"
  favicon: Images/favicon.png
  back-to-top-navigation: true
  repo-url: https://github.com/jschaefer18/my_portfolio.git
  #repo-actions: [issue] #if you want to allow others to report issues on your site uncomment this line

  page-footer: 
    border: true
    left: "Josh Schaefer 2024©"
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/joshua-schaefer-a534b1284/

  navbar:
    background: primary
    search: true   
    right:
      - text: "Home"
        file: index.qmd
      - text: "Objective Statement"
        file: objective.qmd
      - text: "Education"
        file: education.qmd
      - text: "Experience"
        file: experience.qmd
      - text: "Skills & Abilities"
        file: skills.qmd
      - text: "Projects"
        file: projects.qmd
      - text: "Interests"
        file: interests.qmd
      
  # sidebar:
  #   - title: "Match_Name_in_Navbar_Above"
  #     style: "docked"
  #     background: light
  #     contents:
  #       - text: "Match_Name_in_Navbar_Above"
  #         file: Match_Name_in_Navbar_Above.qmd
  #       - text: "---"
  #       - text: "2nd Sidebar Link"
  #         file: path_2.qmd
  #       - text: "---"
  #       - text: "2nd Sidebar Link"
  #         file: path_3.qmd
  #       - text: "---"
  #       #continue the pattern if you need more links
  #       #copy paste from title and keep it indented to sidebar to add additonal sidebar navigation for other pages

format:  
  html:
    theme: #see this link to customize the theme with css (https://quarto.org/docs/output-formats/html-themes.html#dark-mode)
      light: flatly # more themes can be found [here](https://quarto.org/docs/output-formats/html-themes.html)
      dark: darkly
      #light: cosmo
      #dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true



